import React, { useState } from 'react';
import { CalculatedPerformanceReport, Associate } from '../../types';
import { X, Copy, Check, Download, Printer, FileText } from 'lucide-react';

interface ExportReportModalProps {
  report: CalculatedPerformanceReport;
  associate: Associate;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ report, associate, onClose }) => {
  const [copied, setCopied] = useState(false);

  const reportText = `================================================================================
PSIOG ENGINEERING PERFORMANCE REVIEW DOSSIER
Evaluation Period: ${report.periodLabel} (${report.periodStart} to ${report.periodEnd})
Generated by: Psiog Pulse Intelligent Engineering Engine
================================================================================

1. ASSOCIATE PROFILE
--------------------------------------------------------------------------------
Name:             ${associate.name}
Role / Title:     ${associate.title}
Primary Offering: ${associate.primaryOffering}
Corporate Email:  ${associate.email}
Overall Score:    ${report.overallScore} / 100
Rating Band:      ${report.ratingBand}

2. TIME-BOUND TENURE & ATTRIBUTION BREAKDOWN
--------------------------------------------------------------------------------
${report.tenureSegments.map(s => `• ${s.projectName} [${s.offering}]
  Tenure: ${s.startDate} to ${s.endDate} (${s.activeCalendarDays} calendar days, ${s.effectiveWorkingDays} effective days)
  Assigned Role: ${s.role} (Allocation: ${s.allocationPercentage}%)
  Output: ${s.activitiesCount.tickets} tickets, ${s.activitiesCount.prs} PRs, ${s.activitiesCount.reviews} reviews, ${s.activitiesCount.docs} SharePoint docs`).join('\n\n')}

3. MULTI-DIMENSIONAL SCORECARD
--------------------------------------------------------------------------------
• Velocity & Delivery:         ${report.dimensions.delivery.score}/100 (Weight: ${Math.round(report.dimensions.delivery.weight * 100)}%)
  Target: ${report.dimensions.delivery.benchmarkTarget}
  Metrics: ${JSON.stringify(report.dimensions.delivery.rawMetrics)}

• Code Quality & Stability:    ${report.dimensions.quality.score}/100 (Weight: ${Math.round(report.dimensions.quality.weight * 100)}%)
  Target: ${report.dimensions.quality.benchmarkTarget}
  Metrics: ${JSON.stringify(report.dimensions.quality.rawMetrics)}

• Peer Code Review Rigor:      ${report.dimensions.review.score}/100 (Weight: ${Math.round(report.dimensions.review.weight * 100)}%)
  Target: ${report.dimensions.review.benchmarkTarget}
  Metrics: ${JSON.stringify(report.dimensions.review.rawMetrics)}

• Architecture & Docs:         ${report.dimensions.documentation.score}/100 (Weight: ${Math.round(report.dimensions.documentation.weight * 100)}%)
  Target: ${report.dimensions.documentation.benchmarkTarget}
  Metrics: ${JSON.stringify(report.dimensions.documentation.rawMetrics)}

• Operational Reliability:     ${report.dimensions.reliability.score}/100 (Weight: ${Math.round(report.dimensions.reliability.weight * 100)}%)
  Target: ${report.dimensions.reliability.benchmarkTarget}
  Metrics: ${JSON.stringify(report.dimensions.reliability.rawMetrics)}

4. FAIRNESS & CONTEXT ADJUSTMENTS
--------------------------------------------------------------------------------
${report.contextAdjustments.notesApplied.length > 0 
  ? report.contextAdjustments.notesApplied.map(n => `- [${n.category}] ${n.description} (Adjustment: ${n.baselineAdjustmentPercent}%, recorded by ${n.authorName})`).join('\n')
  : 'None recorded for this period.'}

5. AI NARRATIVE & EXECUTIVE SUMMARY
--------------------------------------------------------------------------------
${report.aiInsights.executiveSummary}

Key Strengths:
${report.aiInsights.keyStrengths.map(s => `+ ${s}`).join('\n')}

Growth & Coaching Areas:
${report.aiInsights.growthAreas.map(g => `- ${g}`).join('\n')}

Anti-Gaming Status: ${report.antiGamingFlags.length === 0 ? 'Clean (0 flags)' : `${report.antiGamingFlags.length} flagged patterns requiring Lead review`}
================================================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Psiog-Performance-${associate.name.replace(/\s+/g, '-')}-${report.periodLabel}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-content" style={{ maxWidth: '750px' }} onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div className="stat-icon emerald" style={{ width: '38px', height: '38px' }}>
              <FileText size={18} />
            </div>
            <div>
              <h3 style={{ fontSize: '1.1rem' }}>Export Performance Appraisal Dossier</h3>
              <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Official data-backed assessment report for {associate.name} ({report.periodLabel})
              </p>
            </div>
          </div>
          <button className="btn btn-secondary btn-sm" onClick={onClose} style={{ padding: '6px' }}>
            <X size={18} />
          </button>
        </div>

        <div className="modal-body">
          <textarea
            readOnly
            value={reportText}
            style={{
              width: '100%',
              height: '360px',
              fontFamily: 'JetBrains Mono',
              fontSize: '0.78rem',
              background: '#0d1321',
              color: '#c7d2fe',
              border: '1px solid var(--border-color)',
              borderRadius: 'var(--radius-md)',
              padding: '16px',
              outline: 'none',
              resize: 'none',
              lineHeight: 1.45
            }}
          />
        </div>

        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={handleCopy}>
            {copied ? <Check size={14} color="var(--accent-emerald)" /> : <Copy size={14} />}
            <span>{copied ? 'Copied Dossier!' : 'Copy to Clipboard'}</span>
          </button>
          <button className="btn btn-primary" onClick={handleDownload}>
            <Download size={14} /> Download File (.txt)
          </button>
        </div>
      </div>
    </div>
  );
};
